name: Run Go Tests in 2023 Directory

on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23'

      - name: Run tests in 2023 directory
        run: |
          cd 2023
          for dir in */; do
            [ -d "$dir" ] && (cd "$dir" && go test)
          done
